# 1. Direcci�n de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# 2. Usuario y Contrase�a
spring.datasource.username=root
spring.datasource.password=Jonathantromb26-.

# 3. Hibernate (Crea la tabla Producto en MySQL)
spring.jpa.hibernate.ddl-auto=update

# 4. Consola y Nombre
spring.jpa.show-sql=true
spring.application.name=inventari|o